# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161103_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_step',
            field=models.CharField(choices=[(b'ExtractionStep', b'Extraction'), (b'StandardizationStep', b'Standardization'), (b'SegmentationStep', b'Segmentation'), (b'SchemaMatchingStep', b'Schema matching'), (b'IndexingStep', b'Indexing'), (b'ComparisonStep', b'Comparison'), (b'ClassificationStep', b'Classification'), (b'DataFusionStep', b'Data fusion'), (b'ExportStep', b'Export')], default=None, max_length=30),
        ),
    ]
