# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161226_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepconfig',
            name='config',
            field=jsonfield.fields.JSONField(verbose_name=True),
        ),
        migrations.AlterField(
            model_name='stepconfig',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main.Project'),
        ),
    ]
