# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-01 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161231_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='segment_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
