# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_segment_skipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='segment_skipped',
            new_name='segmentation_skipped',
        ),
    ]
