"""
This file contains global output fields that can be used by the segmentation modules
Each output field has its own semantics and should be self-explanatory
The purpose of these global output fields is to provide compatibility among
all the segmentation modules that may coexist on the framework.
The developer of the segmentation module is allowed to use custom output
fields though.
"""
TITLE = "Title"
GIVEN_NAME = "Given-name"
FIRST_NAME = "First-name"
SECOND_NAME = "Second-name"
NICK_NAME = "Nick-name"
SURNAME = "Surname"
BUILDING_NAME = "Building name"
WAYFARE_NUMBER = "Wayfare number"
WAYFARE_NAME = "Wayfare name"
WAYFARE_TYPE = "Wayfare type"
POSTAL_ADDRESS_NUMBER = "Postal address number"
POSTAL_ADDRESS_TYPE = "Postal address type"
UNIT_PREFIX = "Unit prefix"
UNIT_TYPE = "Unit type"
UNIT_NUMBER = "Unit number"
UNIT_SUFFIX = "Unit suffix"
INSTITUTION_NAME = "Institution name"
INSTITUTION_TYPE = "Institution type"
LOCALITY_NAME = "Locality name"
TERRITORY = "Territory"
ZIPCODE = "Zipcode"
COUNTRY = "Country"
DATE = "Date"
DAY = "Day"
MONTH = "Month"
YEAR = "Year"
HOURS = "Hour"
SECONDS = "Seconds"
TIME = "Time"
AGE = "Age"
BIRTHDAY = "Birthday"
COUNTRY_CODE = "Telephone country code"
AREA_CODE = "Telephone area code"
TEL_NUMBER = "Telephone number"
EXTENSION = "Telephone extension"
